"""Add last few things

Revision ID: 401ad4dabd7d
Revises: ec853c5b58c8
Create Date: 2022-08-07 15:13:33.953607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401ad4dabd7d'
down_revision = 'ec853c5b58c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
